/********************************************************************************
** Form generated from reading UI file 'CL.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CL_H
#define UI_CL_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_gestionCl
{
public:
    QTabWidget *tabWidget_2;
    QWidget *widget;
    QTabWidget *tabWidget_4;
    QWidget *tab_8;
    QGroupBox *groupBox_4;
    QLabel *label_28;
    QLabel *label_33;
    QLabel *label_34;
    QPushButton *pushButton_4;
    QLabel *label_37;
    QLineEdit *lineEdit_5;
    QComboBox *comboLiv;
    QComboBox *comboClient;
    QComboBox *comboCat;
    QLabel *label_2;
    QLabel *label_12;
    QLabel *label_3;
    QWidget *tab_9;
    QPushButton *pushButton_14;
    QTableView *tableView;
    QLineEdit *lineEdit_10;
    QLabel *label_15;
    QLabel *label_50;
    QPushButton *pushButton_8;
    QPushButton *pushButton_5;
    QLabel *label_14;
    QLabel *label_36;
    QWidget *tab_10;
    QGroupBox *groupBox_5;
    QLabel *label_41;
    QLabel *label_47;
    QLabel *label_48;
    QPushButton *pushButton_7;
    QLabel *label_49;
    QComboBox *comboLiv_2;
    QComboBox *comboClient_2;
    QComboBox *comboCommande;
    QComboBox *comboCat2;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_16;
    QLabel *label_32;
    QWidget *tab_11;
    QGroupBox *groupBox_6;
    QPushButton *pushButton_6;
    QLabel *label_45;
    QLabel *label_30;
    QComboBox *comboCommande_2;
    QLabel *label_42;
    QLabel *label_43;
    QWidget *tab_4;
    QTabWidget *tabWidget_3;
    QWidget *tab_3;
    QGroupBox *groupBox;
    QGroupBox *groupBox_7;
    QPushButton *pushButton;
    QLabel *label_5;
    QLabel *label_9;
    QLabel *label_11;
    QLabel *label_7;
    QLabel *label_13;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLabel *label;
    QWidget *tab_5;
    QLabel *label_27;
    QPushButton *pushButton_12;
    QTableView *tableView_2;
    QLineEdit *lineEdit_20;
    QLabel *label_21;
    QLabel *label_23;
    QLabel *label_29;
    QLabel *label_51;
    QLabel *label_10;
    QWidget *tab_6;
    QGroupBox *groupBox_2;
    QLabel *label_22;
    QLineEdit *lineEdit_7;
    QLabel *label_24;
    QLabel *label_25;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLabel *label_26;
    QPushButton *pushButton_2;
    QComboBox *combolk;
    QLabel *label_20;
    QLabel *label_6;
    QWidget *tab_7;
    QGroupBox *groupBox_3;
    QPushButton *pushButton_3;
    QLabel *label_31;
    QLabel *label_19;
    QComboBox *combols;
    QLabel *label_17;
    QWidget *tab;
    QLabel *label_123;
    QLabel *label_124;
    QLineEdit *port_2;
    QLabel *label_125;
    QPlainTextEdit *msg_2;
    QLabel *label_126;
    QLabel *label_127;
    QLineEdit *uname_2;
    QLabel *label_128;
    QLineEdit *paswd_2;
    QLineEdit *subject_2;
    QLabel *label_129;
    QPushButton *sendBtn;
    QPushButton *browseBtn;
    QLineEdit *server_2;
    QLineEdit *file_2;
    QLineEdit *rcpt_2;
    QLabel *label_130;
    QPushButton *exitBtn;
    QLabel *label_18;

    void setupUi(QDialog *gestionCl)
    {
        if (gestionCl->objectName().isEmpty())
            gestionCl->setObjectName(QStringLiteral("gestionCl"));
        gestionCl->resize(851, 478);
        tabWidget_2 = new QTabWidget(gestionCl);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(-10, 20, 931, 481));
        QFont font;
        font.setFamily(QStringLiteral("Lucida Calligraphy"));
        font.setPointSize(15);
        font.setBold(true);
        font.setItalic(false);
        font.setWeight(75);
        tabWidget_2->setFont(font);
        tabWidget_2->setStyleSheet(QStringLiteral("color: rgb(85, 170, 255);"));
        widget = new QWidget();
        widget->setObjectName(QStringLiteral("widget"));
        tabWidget_4 = new QTabWidget(widget);
        tabWidget_4->setObjectName(QStringLiteral("tabWidget_4"));
        tabWidget_4->setGeometry(QRect(0, 0, 961, 471));
        QFont font1;
        font1.setFamily(QStringLiteral("Lucida Calligraphy"));
        font1.setPointSize(10);
        tabWidget_4->setFont(font1);
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        groupBox_4 = new QGroupBox(tab_8);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 30, 711, 361));
        QFont font2;
        font2.setFamily(QStringLiteral("Lucida Calligraphy"));
        font2.setPointSize(14);
        font2.setBold(true);
        font2.setWeight(75);
        groupBox_4->setFont(font2);
        groupBox_4->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
""));
        label_28 = new QLabel(groupBox_4);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(140, 130, 171, 31));
        QFont font3;
        font3.setFamily(QStringLiteral("Lucida Calligraphy"));
        font3.setPointSize(12);
        label_28->setFont(font3);
        label_33 = new QLabel(groupBox_4);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(140, 60, 171, 31));
        label_33->setFont(font3);
        label_34 = new QLabel(groupBox_4);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(130, 210, 171, 31));
        label_34->setFont(font3);
        pushButton_4 = new QPushButton(groupBox_4);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(310, 330, 101, 31));
        QFont font4;
        font4.setFamily(QStringLiteral("Lucida Calligraphy"));
        font4.setPointSize(11);
        font4.setBold(true);
        font4.setWeight(75);
        pushButton_4->setFont(font4);
        pushButton_4->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
"background-image:rgb(255, 170, 255)"));
        label_37 = new QLabel(groupBox_4);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(130, 270, 201, 31));
        label_37->setFont(font3);
        lineEdit_5 = new QLineEdit(groupBox_4);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(430, 70, 121, 22));
        lineEdit_5->setMaxLength(5);
        comboLiv = new QComboBox(groupBox_4);
        comboLiv->setObjectName(QStringLiteral("comboLiv"));
        comboLiv->setGeometry(QRect(430, 280, 121, 22));
        comboClient = new QComboBox(groupBox_4);
        comboClient->setObjectName(QStringLiteral("comboClient"));
        comboClient->setGeometry(QRect(430, 130, 121, 22));
        comboCat = new QComboBox(groupBox_4);
        comboCat->setObjectName(QStringLiteral("comboCat"));
        comboCat->setGeometry(QRect(430, 200, 121, 22));
        label_2 = new QLabel(tab_8);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(-110, 0, 1051, 441));
        label_2->setStyleSheet(QStringLiteral("background-image:url(:/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg)"));
        label_12 = new QLabel(tab_8);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(20, 20, 47, 61));
        label_3 = new QLabel(tab_8);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(0, 0, 841, 461));
        label_3->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg")));
        tabWidget_4->addTab(tab_8, QString());
        label_3->raise();
        label_2->raise();
        groupBox_4->raise();
        label_12->raise();
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        pushButton_14 = new QPushButton(tab_9);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(490, 170, 361, 81));
        QFont font5;
        font5.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font5.setPointSize(14);
        font5.setBold(false);
        font5.setItalic(false);
        font5.setUnderline(false);
        font5.setWeight(50);
        font5.setStrikeOut(false);
        pushButton_14->setFont(font5);
        pushButton_14->setStyleSheet(QLatin1String("background-color:rgb(255, 179, 245);\n"
"color:rgb(96, 96, 144);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
""));
        QIcon icon;
        icon.addFile(QStringLiteral("../ProQtCppF/tri.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_14->setIcon(icon);
        pushButton_14->setIconSize(QSize(100, 121));
        tableView = new QTableView(tab_9);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(30, 30, 421, 331));
        lineEdit_10 = new QLineEdit(tab_9);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(580, 70, 201, 31));
        label_15 = new QLabel(tab_9);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(530, 180, 61, 61));
        label_15->setStyleSheet(QStringLiteral("background-image:url(:/tri.png)"));
        label_50 = new QLabel(tab_9);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(470, -10, 371, 81));
        QFont font6;
        font6.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font6.setPointSize(14);
        font6.setBold(false);
        font6.setItalic(false);
        font6.setWeight(50);
        label_50->setFont(font6);
        label_50->setStyleSheet(QLatin1String("color:rgb(96, 96, 144);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"\n"
""));
        pushButton_8 = new QPushButton(tab_9);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(680, 320, 141, 51));
        pushButton_8->setStyleSheet(QLatin1String("background-color:rgb(170, 170, 255);\n"
"color:rgb(96, 96, 144);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
""));
        pushButton_5 = new QPushButton(tab_9);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(490, 320, 131, 51));
        pushButton_5->setStyleSheet(QLatin1String("background-color:rgb(170, 170, 255);\n"
"color:rgb(96, 96, 144);\n"
"font: 75 18pt \"MS Shell Dlg 2\";"));
        label_14 = new QLabel(tab_9);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(-40, -250, 2281, 2751));
        label_14->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/macaron.jpg")));
        label_36 = new QLabel(tab_9);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(500, 180, 61, 61));
        label_36->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/tri.png")));
        tabWidget_4->addTab(tab_9, QString());
        label_14->raise();
        pushButton_14->raise();
        tableView->raise();
        lineEdit_10->raise();
        label_15->raise();
        label_50->raise();
        pushButton_8->raise();
        pushButton_5->raise();
        label_36->raise();
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        groupBox_5 = new QGroupBox(tab_10);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(70, 20, 711, 381));
        groupBox_5->setFont(font2);
        groupBox_5->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
""));
        label_41 = new QLabel(groupBox_5);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(120, 130, 171, 31));
        label_41->setFont(font3);
        label_47 = new QLabel(groupBox_5);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(120, 60, 171, 31));
        label_47->setFont(font3);
        label_48 = new QLabel(groupBox_5);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(110, 200, 171, 31));
        label_48->setFont(font3);
        pushButton_7 = new QPushButton(groupBox_5);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(310, 310, 101, 31));
        pushButton_7->setFont(font4);
        pushButton_7->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
"background-image:rgb(255, 170, 255)"));
        label_49 = new QLabel(groupBox_5);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(80, 260, 171, 31));
        label_49->setFont(font3);
        comboLiv_2 = new QComboBox(groupBox_5);
        comboLiv_2->setObjectName(QStringLiteral("comboLiv_2"));
        comboLiv_2->setGeometry(QRect(430, 260, 121, 22));
        comboClient_2 = new QComboBox(groupBox_5);
        comboClient_2->setObjectName(QStringLiteral("comboClient_2"));
        comboClient_2->setGeometry(QRect(430, 130, 121, 22));
        comboCommande = new QComboBox(groupBox_5);
        comboCommande->setObjectName(QStringLiteral("comboCommande"));
        comboCommande->setGeometry(QRect(430, 60, 121, 22));
        comboCat2 = new QComboBox(groupBox_5);
        comboCat2->setObjectName(QStringLiteral("comboCat2"));
        comboCat2->setGeometry(QRect(430, 200, 121, 22));
        label_38 = new QLabel(tab_10);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(530, 410, 201, 31));
        label_38->setFont(font3);
        label_39 = new QLabel(tab_10);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(510, 410, 201, 31));
        label_39->setFont(font3);
        label_16 = new QLabel(tab_10);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(-80, -80, 1201, 611));
        label_16->setStyleSheet(QStringLiteral("background-image:url(:/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg)"));
        label_32 = new QLabel(tab_10);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 0, 931, 511));
        label_32->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg")));
        tabWidget_4->addTab(tab_10, QString());
        label_32->raise();
        label_16->raise();
        label_38->raise();
        label_39->raise();
        groupBox_5->raise();
        tab_11 = new QWidget();
        tab_11->setObjectName(QStringLiteral("tab_11"));
        groupBox_6 = new QGroupBox(tab_11);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(230, 50, 341, 331));
        groupBox_6->setFont(font2);
        groupBox_6->setLayoutDirection(Qt::LeftToRight);
        groupBox_6->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
"\n"
""));
        pushButton_6 = new QPushButton(groupBox_6);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(60, 220, 211, 61));
        pushButton_6->setFont(font4);
        pushButton_6->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
"background-image:rgb(255, 170, 255)"));
        QIcon icon1;
        icon1.addFile(QStringLiteral("../../../../Downloads/poubelle.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_6->setIcon(icon1);
        pushButton_6->setIconSize(QSize(150, 150));
        label_45 = new QLabel(groupBox_6);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(90, 100, 171, 31));
        label_45->setFont(font6);
        label_45->setStyleSheet(QStringLiteral("font: 14pt \"MS Shell Dlg 2\";"));
        label_30 = new QLabel(groupBox_6);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(80, 220, 61, 61));
        label_30->setStyleSheet(QStringLiteral("background-image:url(:/poubelle.png)"));
        comboCommande_2 = new QComboBox(groupBox_6);
        comboCommande_2->setObjectName(QStringLiteral("comboCommande_2"));
        comboCommande_2->setGeometry(QRect(120, 150, 101, 22));
        label_42 = new QLabel(groupBox_6);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(60, 220, 71, 61));
        label_42->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/poubelle.png")));
        label_43 = new QLabel(tab_11);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(0, 0, 1261, 601));
        label_43->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg")));
        tabWidget_4->addTab(tab_11, QString());
        label_43->raise();
        groupBox_6->raise();
        tabWidget_2->addTab(widget, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        tabWidget_3 = new QTabWidget(tab_4);
        tabWidget_3->setObjectName(QStringLiteral("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(10, 0, 961, 471));
        tabWidget_3->setFont(font1);
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        groupBox = new QGroupBox(tab_3);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, -60, 921, 461));
        groupBox->setFont(font2);
        groupBox->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
""));
        groupBox_7 = new QGroupBox(groupBox);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(0, 70, 721, 391));
        groupBox_7->setFont(font2);
        groupBox_7->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
""));
        pushButton = new QPushButton(groupBox_7);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(380, 330, 111, 41));
        pushButton->setFont(font4);
        pushButton->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
"background-image:rgb(255, 170, 255)"));
        label_5 = new QLabel(groupBox_7);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 10, 231, 21));
        label_5->setMinimumSize(QSize(181, 21));
        QFont font7;
        font7.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font7.setPointSize(16);
        font7.setBold(false);
        font7.setItalic(false);
        font7.setWeight(9);
        label_5->setFont(font7);
        label_5->setStyleSheet(QStringLiteral("font: 75 16pt \"MS Shell Dlg 2\";"));
        label_9 = new QLabel(groupBox_7);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 80, 91, 31));
        label_9->setFont(font3);
        label_11 = new QLabel(groupBox_7);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 200, 171, 31));
        label_11->setFont(font3);
        label_7 = new QLabel(groupBox_7);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 140, 171, 31));
        label_7->setFont(font3);
        label_13 = new QLabel(groupBox_7);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 270, 171, 31));
        label_13->setFont(font3);
        lineEdit_17 = new QLineEdit(groupBox_7);
        lineEdit_17->setObjectName(QStringLiteral("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(220, 270, 201, 20));
        lineEdit_15 = new QLineEdit(groupBox_7);
        lineEdit_15->setObjectName(QStringLiteral("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(220, 200, 201, 20));
        lineEdit = new QLineEdit(groupBox_7);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(220, 140, 201, 20));
        lineEdit_2 = new QLineEdit(groupBox_7);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(220, 80, 201, 20));
        lineEdit_2->setMaxLength(5);
        label = new QLabel(tab_3);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(-64, -10, 911, 431));
        label->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg")));
        tabWidget_3->addTab(tab_3, QString());
        label->raise();
        groupBox->raise();
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        label_27 = new QLabel(tab_5);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(-70, -30, 981, 461));
        label_27->setPixmap(QPixmap(QString::fromUtf8("../../../../Downloads/893983.jpg")));
        pushButton_12 = new QPushButton(tab_5);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(560, 260, 231, 81));
        pushButton_12->setFont(font5);
        pushButton_12->setStyleSheet(QLatin1String("background-color:rgb(255, 179, 245);\n"
"color:rgb(96, 96, 144);\n"
"font: 14pt \"MS Shell Dlg 2\";"));
        QIcon icon2;
        icon2.addFile(QStringLiteral("../../../../Downloads/tri.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_12->setIcon(icon2);
        pushButton_12->setIconSize(QSize(100, 121));
        tableView_2 = new QTableView(tab_5);
        tableView_2->setObjectName(QStringLiteral("tableView_2"));
        tableView_2->setGeometry(QRect(30, 30, 421, 351));
        lineEdit_20 = new QLineEdit(tab_5);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(550, 140, 191, 41));
        label_21 = new QLabel(tab_5);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(0, 0, 901, 441));
        label_21->setStyleSheet(QStringLiteral("background-image:url(:/macaron.jpg)"));
        label_23 = new QLabel(tab_5);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(670, 290, 47, 13));
        label_29 = new QLabel(tab_5);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(570, 270, 61, 61));
        label_29->setStyleSheet(QStringLiteral("background-image:url(:/tri.png)"));
        label_29->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/tri.png")));
        label_51 = new QLabel(tab_5);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(480, 50, 431, 71));
        QFont font8;
        font8.setFamily(QStringLiteral("MS Shell Dlg 2"));
        font8.setPointSize(13);
        font8.setBold(false);
        font8.setItalic(false);
        font8.setWeight(50);
        label_51->setFont(font8);
        label_51->setStyleSheet(QLatin1String("color:rgb(96, 96, 144);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
""));
        label_10 = new QLabel(tab_5);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(0, -240, 1351, 2721));
        label_10->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/macaron.jpg")));
        tabWidget_3->addTab(tab_5, QString());
        label_10->raise();
        label_21->raise();
        label_27->raise();
        pushButton_12->raise();
        tableView_2->raise();
        lineEdit_20->raise();
        label_23->raise();
        label_29->raise();
        label_51->raise();
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        groupBox_2 = new QGroupBox(tab_6);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(0, 10, 731, 391));
        groupBox_2->setFont(font2);
        groupBox_2->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
""));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(40, 130, 61, 31));
        label_22->setFont(font3);
        lineEdit_7 = new QLineEdit(groupBox_2);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(270, 140, 201, 20));
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(40, 60, 91, 31));
        label_24->setMinimumSize(QSize(91, 0));
        label_24->setFont(font3);
        label_25 = new QLabel(groupBox_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(40, 200, 61, 31));
        label_25->setFont(font3);
        lineEdit_18 = new QLineEdit(groupBox_2);
        lineEdit_18->setObjectName(QStringLiteral("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(270, 200, 201, 22));
        lineEdit_19 = new QLineEdit(groupBox_2);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(270, 270, 201, 22));
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(40, 270, 171, 31));
        label_26->setFont(font3);
        pushButton_2 = new QPushButton(groupBox_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(420, 330, 121, 41));
        pushButton_2->setFont(font4);
        pushButton_2->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
"background-image:rgb(255, 170, 255)"));
        combolk = new QComboBox(groupBox_2);
        combolk->setObjectName(QStringLiteral("combolk"));
        combolk->setGeometry(QRect(270, 70, 201, 22));
        label_20 = new QLabel(tab_6);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(-20, 0, 921, 521));
        label_20->setStyleSheet(QStringLiteral("background-image:url(:/1484065617_22184.jpg)"));
        label_6 = new QLabel(tab_6);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(-4, 0, 901, 621));
        label_6->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg")));
        tabWidget_3->addTab(tab_6, QString());
        label_6->raise();
        label_20->raise();
        groupBox_2->raise();
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        groupBox_3 = new QGroupBox(tab_7);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(250, 50, 331, 311));
        groupBox_3->setFont(font2);
        groupBox_3->setLayoutDirection(Qt::LeftToRight);
        groupBox_3->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
""));
        pushButton_3 = new QPushButton(groupBox_3);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(60, 200, 191, 61));
        pushButton_3->setFont(font4);
        pushButton_3->setStyleSheet(QLatin1String("color: rgb(255, 80, 97);\n"
"background-image:rgb(255, 170, 255)"));
        pushButton_3->setIcon(icon1);
        pushButton_3->setIconSize(QSize(150, 150));
        label_31 = new QLabel(groupBox_3);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(70, 80, 271, 31));
        label_31->setFont(font6);
        label_31->setStyleSheet(QStringLiteral("font: 14pt \"MS Shell Dlg 2\";"));
        label_19 = new QLabel(groupBox_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(60, 200, 61, 61));
        label_19->setStyleSheet(QStringLiteral("background-image:url(:/poubelle.png)"));
        label_19->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/poubelle.png")));
        combols = new QComboBox(groupBox_3);
        combols->setObjectName(QStringLiteral("combols"));
        combols->setGeometry(QRect(100, 140, 101, 22));
        label_17 = new QLabel(tab_7);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(-10, -30, 1321, 591));
        label_17->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg")));
        tabWidget_3->addTab(tab_7, QString());
        label_17->raise();
        groupBox_3->raise();
        tabWidget_2->addTab(tab_4, QString());
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        label_123 = new QLabel(tab);
        label_123->setObjectName(QStringLiteral("label_123"));
        label_123->setGeometry(QRect(40, 180, 67, 20));
        QFont font9;
        font9.setPointSize(12);
        font9.setBold(true);
        font9.setUnderline(false);
        font9.setWeight(75);
        label_123->setFont(font9);
        label_123->setStyleSheet(QStringLiteral("color:rgb(255, 85, 127)"));
        label_124 = new QLabel(tab);
        label_124->setObjectName(QStringLiteral("label_124"));
        label_124->setGeometry(QRect(40, 119, 121, 21));
        QFont font10;
        font10.setPointSize(13);
        font10.setBold(true);
        font10.setUnderline(false);
        font10.setWeight(75);
        label_124->setFont(font10);
        label_124->setStyleSheet(QStringLiteral("color:rgb(255, 85, 127)"));
        port_2 = new QLineEdit(tab);
        port_2->setObjectName(QStringLiteral("port_2"));
        port_2->setGeometry(QRect(180, 60, 256, 20));
        port_2->setStyleSheet(QStringLiteral("background-color:rgb(255, 226, 247)"));
        label_125 = new QLabel(tab);
        label_125->setObjectName(QStringLiteral("label_125"));
        label_125->setGeometry(QRect(40, 210, 102, 25));
        label_125->setFont(font9);
        label_125->setStyleSheet(QStringLiteral("color:rgb(255, 85, 127)"));
        msg_2 = new QPlainTextEdit(tab);
        msg_2->setObjectName(QStringLiteral("msg_2"));
        msg_2->setGeometry(QRect(150, 300, 271, 121));
        msg_2->setStyleSheet(QStringLiteral("background-color:rgb(255, 226, 247)"));
        label_126 = new QLabel(tab);
        label_126->setObjectName(QStringLiteral("label_126"));
        label_126->setGeometry(QRect(40, 61, 131, 20));
        label_126->setFont(font9);
        label_126->setStyleSheet(QStringLiteral("color:rgb(255, 85, 127)"));
        label_127 = new QLabel(tab);
        label_127->setObjectName(QStringLiteral("label_127"));
        label_127->setGeometry(QRect(40, 149, 104, 21));
        label_127->setFont(font10);
        label_127->setStyleSheet(QStringLiteral("color:rgb(255, 85, 127)"));
        uname_2 = new QLineEdit(tab);
        uname_2->setObjectName(QStringLiteral("uname_2"));
        uname_2->setGeometry(QRect(180, 90, 256, 20));
        uname_2->setStyleSheet(QStringLiteral("background-color:rgb(255, 226, 247)"));
        label_128 = new QLabel(tab);
        label_128->setObjectName(QStringLiteral("label_128"));
        label_128->setGeometry(QRect(30, 250, 231, 51));
        label_128->setFont(font9);
        label_128->setStyleSheet(QStringLiteral("color:rgb(255, 85, 127)"));
        paswd_2 = new QLineEdit(tab);
        paswd_2->setObjectName(QStringLiteral("paswd_2"));
        paswd_2->setGeometry(QRect(180, 120, 256, 20));
        paswd_2->setStyleSheet(QStringLiteral("background-color:rgb(255, 226, 247)"));
        paswd_2->setEchoMode(QLineEdit::Password);
        subject_2 = new QLineEdit(tab);
        subject_2->setObjectName(QStringLiteral("subject_2"));
        subject_2->setGeometry(QRect(180, 180, 256, 20));
        subject_2->setStyleSheet(QStringLiteral("background-color:rgb(255, 226, 247)"));
        label_129 = new QLabel(tab);
        label_129->setObjectName(QStringLiteral("label_129"));
        label_129->setGeometry(QRect(40, 30, 106, 20));
        QPalette palette;
        QBrush brush(QColor(255, 85, 127, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush1(QColor(255, 85, 127, 128));
        brush1.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush1);
#endif
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush2(QColor(255, 85, 127, 128));
        brush2.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush2);
#endif
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        QBrush brush3(QColor(255, 85, 127, 128));
        brush3.setStyle(Qt::NoBrush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush3);
#endif
        label_129->setPalette(palette);
        label_129->setFont(font9);
        label_129->setAutoFillBackground(false);
        label_129->setStyleSheet(QStringLiteral("color:rgb(255, 85, 127)"));
        label_129->setLineWidth(1);
        sendBtn = new QPushButton(tab);
        sendBtn->setObjectName(QStringLiteral("sendBtn"));
        sendBtn->setGeometry(QRect(600, 160, 121, 51));
        sendBtn->setFont(font4);
        sendBtn->setAutoFillBackground(false);
        sendBtn->setStyleSheet(QLatin1String("color:rgb(255, 85, 127);\n"
"background-color:rgb(255, 196, 250)\n"
""));
        browseBtn = new QPushButton(tab);
        browseBtn->setObjectName(QStringLiteral("browseBtn"));
        browseBtn->setGeometry(QRect(360, 220, 75, 23));
        browseBtn->setAutoFillBackground(false);
        browseBtn->setStyleSheet(QLatin1String("color:rgb(255, 85, 127);\n"
"background-color:rgb(255, 196, 250)"));
        server_2 = new QLineEdit(tab);
        server_2->setObjectName(QStringLiteral("server_2"));
        server_2->setGeometry(QRect(180, 30, 256, 20));
        server_2->setStyleSheet(QStringLiteral("background-color:rgb(255, 226, 247)"));
        file_2 = new QLineEdit(tab);
        file_2->setObjectName(QStringLiteral("file_2"));
        file_2->setGeometry(QRect(180, 210, 141, 31));
        file_2->setStyleSheet(QStringLiteral("background-color:rgb(255, 226, 247)"));
        file_2->setReadOnly(true);
        rcpt_2 = new QLineEdit(tab);
        rcpt_2->setObjectName(QStringLiteral("rcpt_2"));
        rcpt_2->setGeometry(QRect(180, 150, 256, 20));
        rcpt_2->setStyleSheet(QStringLiteral("background-color:rgb(255, 226, 247)"));
        label_130 = new QLabel(tab);
        label_130->setObjectName(QStringLiteral("label_130"));
        label_130->setGeometry(QRect(40, 90, 88, 20));
        label_130->setFont(font9);
        label_130->setStyleSheet(QStringLiteral("color:rgb(255, 85, 127)"));
        exitBtn = new QPushButton(tab);
        exitBtn->setObjectName(QStringLiteral("exitBtn"));
        exitBtn->setGeometry(QRect(580, 330, 75, 41));
        exitBtn->setAutoFillBackground(false);
        exitBtn->setStyleSheet(QLatin1String("color:rgb(255, 85, 127);\n"
"background-color:rgb(255, 196, 250)"));
        label_18 = new QLabel(tab);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 0, 1281, 631));
        label_18->setPixmap(QPixmap(QString::fromUtf8("../../Pictures/i/Alinka-Shemeluyk_Sweets_YkxmSWdYdw.jpg")));
        tabWidget_2->addTab(tab, QString());
        label_18->raise();
        label_123->raise();
        label_124->raise();
        port_2->raise();
        label_125->raise();
        msg_2->raise();
        label_126->raise();
        label_127->raise();
        uname_2->raise();
        label_128->raise();
        paswd_2->raise();
        subject_2->raise();
        label_129->raise();
        sendBtn->raise();
        browseBtn->raise();
        server_2->raise();
        file_2->raise();
        rcpt_2->raise();
        label_130->raise();
        exitBtn->raise();

        retranslateUi(gestionCl);

        tabWidget_2->setCurrentIndex(1);
        tabWidget_4->setCurrentIndex(0);
        tabWidget_3->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(gestionCl);
    } // setupUi

    void retranslateUi(QDialog *gestionCl)
    {
        gestionCl->setWindowTitle(QApplication::translate("gestionCl", "Dialog", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("gestionCl", "                                Ajouter une Commande", Q_NULLPTR));
        label_28->setText(QApplication::translate("gestionCl", "Client", Q_NULLPTR));
        label_33->setText(QApplication::translate("gestionCl", "ID Commande", Q_NULLPTR));
        label_34->setText(QApplication::translate("gestionCl", "Nom Cat\303\251gorie", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("gestionCl", "Ajouter", Q_NULLPTR));
        label_37->setText(QApplication::translate("gestionCl", "Numero livraison", Q_NULLPTR));
        label_2->setText(QString());
        label_12->setText(QString());
        label_3->setText(QString());
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_8), QApplication::translate("gestionCl", "Ajouter", Q_NULLPTR));
        pushButton_14->setText(QApplication::translate("gestionCl", "      Tri par numero du livraison  ", Q_NULLPTR));
        label_15->setText(QString());
        label_50->setText(QApplication::translate("gestionCl", "recherche par un client ou nom categorie", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("gestionCl", "PDF", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("gestionCl", "Statistique", Q_NULLPTR));
        label_14->setText(QString());
        label_36->setText(QString());
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_9), QApplication::translate("gestionCl", "Afficher", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("gestionCl", "                                Modifier une Commande", Q_NULLPTR));
        label_41->setText(QApplication::translate("gestionCl", "Nom Client", Q_NULLPTR));
        label_47->setText(QApplication::translate("gestionCl", "ID Commande", Q_NULLPTR));
        label_48->setText(QApplication::translate("gestionCl", "Nom Cat\303\251gorie", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("gestionCl", "Modifier", Q_NULLPTR));
        label_49->setText(QApplication::translate("gestionCl", "Num\303\251ro De Livraison", Q_NULLPTR));
        label_38->setText(QApplication::translate("gestionCl", "Num\303\251ro De Livraison", Q_NULLPTR));
        label_39->setText(QApplication::translate("gestionCl", "Num\303\251ro De Livraison", Q_NULLPTR));
        label_16->setText(QString());
        label_32->setText(QString());
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_10), QApplication::translate("gestionCl", "Modifier", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("gestionCl", "Supprimer une commande", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("gestionCl", "supprimer", Q_NULLPTR));
        label_45->setText(QApplication::translate("gestionCl", " Id Commande", Q_NULLPTR));
        label_30->setText(QString());
        label_42->setText(QString());
        label_43->setText(QString());
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_11), QApplication::translate("gestionCl", "Supprimer", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(widget), QApplication::translate("gestionCl", "Commandes", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("gestionCl", "Ajouter une livraison", Q_NULLPTR));
        groupBox_7->setTitle(QString());
        pushButton->setText(QApplication::translate("gestionCl", "Ajouter", Q_NULLPTR));
        label_5->setText(QApplication::translate("gestionCl", "<html><head/><body><p><span style=\" font-weight:600;\">Ajouter une livraison</span></p></body></html>", Q_NULLPTR));
        label_9->setText(QApplication::translate("gestionCl", "Num\303\251ro ", Q_NULLPTR));
        label_11->setText(QApplication::translate("gestionCl", "Date Livraison", Q_NULLPTR));
        label_7->setText(QApplication::translate("gestionCl", "Prix", Q_NULLPTR));
        label_13->setText(QApplication::translate("gestionCl", "Adresse Client", Q_NULLPTR));
        label->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_3), QApplication::translate("gestionCl", "Ajouter", Q_NULLPTR));
        label_27->setText(QString());
        pushButton_12->setText(QApplication::translate("gestionCl", "      Tri  par prix  ", Q_NULLPTR));
        label_21->setText(QString());
        label_23->setText(QString());
        label_29->setText(QString());
        label_51->setText(QApplication::translate("gestionCl", "recherche par numero du livraison ou par date", Q_NULLPTR));
        label_10->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_5), QApplication::translate("gestionCl", "Afficher", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("gestionCl", "Modifier une Livraison", Q_NULLPTR));
        label_22->setText(QApplication::translate("gestionCl", "Prix", Q_NULLPTR));
        label_24->setText(QApplication::translate("gestionCl", "Num\303\251ro ", Q_NULLPTR));
        label_25->setText(QApplication::translate("gestionCl", "Date", Q_NULLPTR));
        label_26->setText(QApplication::translate("gestionCl", "Adresse Client", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("gestionCl", "Modifier", Q_NULLPTR));
        label_20->setText(QString());
        label_6->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_6), QApplication::translate("gestionCl", "Modifier", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("gestionCl", "Supprimer une Livraison", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("gestionCl", "   supprimer", Q_NULLPTR));
        label_31->setText(QApplication::translate("gestionCl", "Num\303\251ro De Livraison", Q_NULLPTR));
        label_19->setText(QString());
        label_17->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_7), QApplication::translate("gestionCl", "Supprimer", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QApplication::translate("gestionCl", "Livraisons", Q_NULLPTR));
        label_123->setText(QApplication::translate("gestionCl", "objet", Q_NULLPTR));
        label_124->setText(QApplication::translate("gestionCl", "mot de passe", Q_NULLPTR));
        port_2->setText(QApplication::translate("gestionCl", "465", Q_NULLPTR));
        label_125->setText(QApplication::translate("gestionCl", "Attachment", Q_NULLPTR));
        label_126->setText(QApplication::translate("gestionCl", "port de serveur ", Q_NULLPTR));
        label_127->setText(QApplication::translate("gestionCl", "destinataire", Q_NULLPTR));
        label_128->setText(QApplication::translate("gestionCl", "Message/date de livraison", Q_NULLPTR));
        paswd_2->setInputMask(QString());
        label_129->setText(QApplication::translate("gestionCl", "serveur stmp", Q_NULLPTR));
        sendBtn->setText(QApplication::translate("gestionCl", "Envoyer", Q_NULLPTR));
        browseBtn->setText(QApplication::translate("gestionCl", "chercher", Q_NULLPTR));
        server_2->setText(QApplication::translate("gestionCl", "smtp.gmail.com", Q_NULLPTR));
        label_130->setText(QApplication::translate("gestionCl", "utilisateur", Q_NULLPTR));
        exitBtn->setText(QApplication::translate("gestionCl", "Exit", Q_NULLPTR));
        label_18->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab), QApplication::translate("gestionCl", "Mailing", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class gestionCl: public Ui_gestionCl {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CL_H
